
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BookCard': typeof import("../components/BookCard.vue")['default']
    'Footer': typeof import("../components/footer/footer.vue")['default']
    'FooterBotomn': typeof import("../components/footer/footerBotomn.vue")['default']
    'FooterColumn': typeof import("../components/footer/footerColumn.vue")['default']
    'FooterTop': typeof import("../components/footer/footerTop.vue")['default']
    'HeaderBottom': typeof import("../components/header/header-bottom.vue")['default']
    'HeaderMain': typeof import("../components/header/header-main.vue")['default']
    'HeaderTop': typeof import("../components/header/header-top.vue")['default']
    'HeroSectionAction': typeof import("../components/hero-section/hero-section-action.vue")['default']
    'HeroSectionBlocks': typeof import("../components/hero-section/hero-section-blocks.vue")['default']
    'HeroSectionCard': typeof import("../components/hero-section/hero-section-card.vue")['default']
    'MainNews': typeof import("../components/main/MainNews.vue")['default']
    'MainNewsSlider': typeof import("../components/main/NewsSlider.vue")['default']
    'MainHeader': typeof import("../components/main/main-header.vue")['default']
    'MainKritery': typeof import("../components/main/main-kritery.vue")['default']
    'MainSearch': typeof import("../components/main/main-search.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBookCard': typeof import("../components/BookCard.vue")['default']
    'LazyFooter': typeof import("../components/footer/footer.vue")['default']
    'LazyFooterBotomn': typeof import("../components/footer/footerBotomn.vue")['default']
    'LazyFooterColumn': typeof import("../components/footer/footerColumn.vue")['default']
    'LazyFooterTop': typeof import("../components/footer/footerTop.vue")['default']
    'LazyHeaderBottom': typeof import("../components/header/header-bottom.vue")['default']
    'LazyHeaderMain': typeof import("../components/header/header-main.vue")['default']
    'LazyHeaderTop': typeof import("../components/header/header-top.vue")['default']
    'LazyHeroSectionAction': typeof import("../components/hero-section/hero-section-action.vue")['default']
    'LazyHeroSectionBlocks': typeof import("../components/hero-section/hero-section-blocks.vue")['default']
    'LazyHeroSectionCard': typeof import("../components/hero-section/hero-section-card.vue")['default']
    'LazyMainNews': typeof import("../components/main/MainNews.vue")['default']
    'LazyMainNewsSlider': typeof import("../components/main/NewsSlider.vue")['default']
    'LazyMainHeader': typeof import("../components/main/main-header.vue")['default']
    'LazyMainKritery': typeof import("../components/main/main-kritery.vue")['default']
    'LazyMainSearch': typeof import("../components/main/main-search.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BookCard: typeof import("../components/BookCard.vue")['default']
export const Footer: typeof import("../components/footer/footer.vue")['default']
export const FooterBotomn: typeof import("../components/footer/footerBotomn.vue")['default']
export const FooterColumn: typeof import("../components/footer/footerColumn.vue")['default']
export const FooterTop: typeof import("../components/footer/footerTop.vue")['default']
export const HeaderBottom: typeof import("../components/header/header-bottom.vue")['default']
export const HeaderMain: typeof import("../components/header/header-main.vue")['default']
export const HeaderTop: typeof import("../components/header/header-top.vue")['default']
export const HeroSectionAction: typeof import("../components/hero-section/hero-section-action.vue")['default']
export const HeroSectionBlocks: typeof import("../components/hero-section/hero-section-blocks.vue")['default']
export const HeroSectionCard: typeof import("../components/hero-section/hero-section-card.vue")['default']
export const MainNews: typeof import("../components/main/MainNews.vue")['default']
export const MainNewsSlider: typeof import("../components/main/NewsSlider.vue")['default']
export const MainHeader: typeof import("../components/main/main-header.vue")['default']
export const MainKritery: typeof import("../components/main/main-kritery.vue")['default']
export const MainSearch: typeof import("../components/main/main-search.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBookCard: typeof import("../components/BookCard.vue")['default']
export const LazyFooter: typeof import("../components/footer/footer.vue")['default']
export const LazyFooterBotomn: typeof import("../components/footer/footerBotomn.vue")['default']
export const LazyFooterColumn: typeof import("../components/footer/footerColumn.vue")['default']
export const LazyFooterTop: typeof import("../components/footer/footerTop.vue")['default']
export const LazyHeaderBottom: typeof import("../components/header/header-bottom.vue")['default']
export const LazyHeaderMain: typeof import("../components/header/header-main.vue")['default']
export const LazyHeaderTop: typeof import("../components/header/header-top.vue")['default']
export const LazyHeroSectionAction: typeof import("../components/hero-section/hero-section-action.vue")['default']
export const LazyHeroSectionBlocks: typeof import("../components/hero-section/hero-section-blocks.vue")['default']
export const LazyHeroSectionCard: typeof import("../components/hero-section/hero-section-card.vue")['default']
export const LazyMainNews: typeof import("../components/main/MainNews.vue")['default']
export const LazyMainNewsSlider: typeof import("../components/main/NewsSlider.vue")['default']
export const LazyMainHeader: typeof import("../components/main/main-header.vue")['default']
export const LazyMainKritery: typeof import("../components/main/main-kritery.vue")['default']
export const LazyMainSearch: typeof import("../components/main/main-search.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
